"""
Bridge between a Unitree Go2 robot and a web frontend, using the official
Unitree WebRTC protocol (the same one the Unitree Go / Unitree Explore
mobile apps use) via the `unitree_webrtc_connect` library. No jailbreak or
firmware modification needed.

Connects to the robot, subscribes to LiDAR / lowstate / sportmodestate /
wireless-controller data, decodes the video track to JPEG frames, and
exposes everything over a small Flask HTTP API for the NERO_GO2 web
dashboard to consume.

Generated by a local qwen2.5-coder:14b model (NERO_GO2 delegation workflow,
ld. docs/13-lokalis-llm-delegalas.md), reviewed and fixed by hand. The
exact RTC_TOPIC key names below are best-effort from the library's public
README — they were NOT verified against the installed library's actual
examples/ source, and MUST be confirmed against a real robot connection
before relying on this in a demo.
"""

import asyncio
import logging
import os
import threading
from typing import Optional

import cv2
from flask import Flask, Response, jsonify

from unitree_webrtc_connect import (
    UnitreeWebRTCConnection,
    WebRTCConnectionMethod,
    RTC_TOPIC,
    AesKeyRequiredError,
    AesKeyRejectedError,
    RobotBusyError,
    LocalSignalingPortError,
)

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger("nero_go2.webrtc_bridge")

app = Flask(__name__)

# --- shared state, one lock guards all of it (simpler than per-key locks,
# and none of these updates are hot enough to need finer granularity) ---
_state_lock = threading.Lock()
_state = {
    "connected": False,
    "latest_jpeg": None,  # type: Optional[bytes]
    "lidar": None,
    "lowstate": None,
    "sportmodestate": None,
    "wireless_controller": None,
}


def _set_state(**kwargs):
    with _state_lock:
        _state.update(kwargs)


def _get_state():
    with _state_lock:
        return dict(_state)


@app.route("/health")
def health():
    s = _get_state()
    return jsonify({"status": "ok", "connected": s["connected"]})


@app.route("/camera.jpg")
def camera_jpeg():
    s = _get_state()
    if s["latest_jpeg"] is None:
        return Response(status=404)
    return Response(s["latest_jpeg"], mimetype="image/jpeg")


@app.route("/lidar")
def lidar():
    s = _get_state()
    if s["lidar"] is None:
        return jsonify({"error": "no lidar data yet"}), 404
    points = s["lidar"]
    if isinstance(points, list) and len(points) > 5000:
        step = len(points) // 5000
        points = points[::step][:5000]
    return jsonify(points)


@app.route("/state")
def state():
    s = _get_state()
    return jsonify(
        {
            "lowstate": s["lowstate"],
            "sportmodestate": s["sportmodestate"],
            "wireless_controller": s["wireless_controller"],
        }
    )


async def _subscribe_forever(conn, topic, state_key):
    """Subscribe to one data-channel topic and keep the latest message in _state.

    NOTE: `subscribe()` here is a best guess at the WebRTCDataChannelPubSub
    API shape (README only documents the class name, not its methods).
    Verify against the installed library before trusting this in a demo.
    """
    try:
        async for message in conn.data_channel_pubsub.subscribe(topic):
            _set_state(**{state_key: message})
    except Exception:
        logger.exception("subscription to %s topic dropped", state_key)


async def _process_video(conn):
    async for frame in conn.video:
        if frame is None:
            continue
        img = frame.to_ndarray(format="bgr24")
        ok, jpeg = cv2.imencode(".jpg", img)
        if ok:
            _set_state(latest_jpeg=jpeg.tobytes())


async def run_bridge():
    ip = os.environ.get("UNITREE_ROBOT_IP", "192.168.123.18")
    aes_key = os.environ.get("UNITREE_AES_128_KEY") or None

    conn_kwargs = {"ip": ip}
    if aes_key:
        conn_kwargs["aes_128_key"] = aes_key

    conn = UnitreeWebRTCConnection(WebRTCConnectionMethod.LocalSTA, **conn_kwargs)

    try:
        await conn.connect()
    except AesKeyRequiredError:
        logger.error(
            "Robot firmware requires a per-device AES-128 key (firmware >= 1.1.15). "
            "Fetch it with `unitree-fetch-aes-key` and set UNITREE_AES_128_KEY."
        )
        return
    except AesKeyRejectedError:
        logger.error("UNITREE_AES_128_KEY was rejected by the robot (wrong key).")
        return
    except RobotBusyError:
        logger.error(
            "Robot refused the connection - another WebRTC client (e.g. the "
            "official app) is already connected. Only one client at a time."
        )
        return
    except LocalSignalingPortError:
        logger.error("Neither port 9991 nor 8081 reachable on %s - check the IP/network.", ip)
        return

    _set_state(connected=True)
    logger.info("connected to Go2 at %s", ip)

    try:
        await asyncio.gather(
            _subscribe_forever(conn, RTC_TOPIC.get("ULIDAR_ARRAY"), "lidar"),
            _subscribe_forever(conn, RTC_TOPIC.get("LOWSTATE"), "lowstate"),
            _subscribe_forever(conn, RTC_TOPIC.get("SPORTMODESTATE"), "sportmodestate"),
            _subscribe_forever(conn, RTC_TOPIC.get("WIRELESS_CONTROLLER"), "wireless_controller"),
            _process_video(conn),
        )
    finally:
        _set_state(connected=False)


def main():
    flask_thread = threading.Thread(
        target=lambda: app.run(host="0.0.0.0", port=5001, threaded=True, use_reloader=False),
        daemon=True,
    )
    flask_thread.start()
    asyncio.run(run_bridge())


if __name__ == "__main__":
    main()
